config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  devise_for :users
  resources :posts
  get "about", to: "static_pages#about"
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true
  validates :content, presence: true

  after_initialize { self.posted_at ||= Time.current }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def authenticate_user!
    if user_signed_in?
      super
    else
      redirect_to root_path, :notice => 'Please sign-in first'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]

  def new
    @post = Post.new
  end

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    post = Post.create(post_params)
    if post.persisted?
      redirect_to post
    else
      flash[:error] = "Unable to save! #{post.errors}"
      redirect_to :new
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :content, :posted_at)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController; end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.slim
header.navbar.navbar-default
  .navbar-inner
    .container-fluid
      = link_to "Low-Key Travels", {}, id: 'logo'
      ul.nav.navbar-nav.navbar-right
        li
          = link_to "Blog", posts_url
        li
          = link_to "About me", about_path
        - if user_signed_in?
          li
            = link_to "Log Out", destroy_user_session_path

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="span6 offset3">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    </div>
  <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SimpleBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<%= render 'layouts/messages' unless flash.empty? %>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.slim
.post-form
  = bootstrap_form_for(@post) do |f|
    .form-errors

    .form-inputs
      = f.text_field :title, class: 'post-title'
      = f.datetime_field :posted_at, label: "Date", class: 'post-date', value: @post.posted_at.getlocal.strftime("%Y-%m-%d %H:%M %z")
      = f.text_area :content, as: :text, class: 'post-content'

    .form-actions
      = f.button :submit, class: "button btn btn-success"
      = link_to 'Back', posts_path, class: "back-button btn btn-danger pull-right"

app/views/posts/_options.html.slim
.options
  span.option
    = link_to 'Edit', edit_post_path(post)
    ||
  span.option
    = link_to 'Destroy', post, confirm: 'Are you sure?', method: :delete

app/views/posts/_post.html.slim
.post
  .post-title
    = link_to post.title, post
    span.post-date
      = post.posted_at.strftime("%B %d, %Y")
  p.post-content
    =raw post.content
= render 'options', post: post if user_signed_in?

app/views/posts/index.html.slim
#posts
  #post-list-header
  #select-page.center

  = link_to 'New Post', new_post_path, class: 'new_post_link' if user_signed_in?
  #post-list
    - @posts.each do |post|
      = render post
  #post-list-footer.center

app/views/posts/new.html.slim
.new-post-page
  .h1 New blog

  = render 'form'

app/views/posts/show.html.slim
#post
  = render @post

app/views/users/sign_in.html.slim
h2 Sign-In
.container-fluid
  = bootstrap_form_for @user, class: "form_vertical", url: root_url do |f|
    = f.email_field :email
    = f.password_field :password
    = f.button :submit